name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ExtractLinks:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Download links_from_readme.txt
      run: |
        curl -L https://raw.githubusercontent.com/Auniquesir/Test/X/QuantumultX_files/links_from_readme.txt -o links_from_readme.txt
        # 检查下载文件是否存在
        if [ ! -f links_from_readme.txt ]; then
          echo "Failed to download the file"
          exit 1
        fi

    - name: Remove duplicate links
      run: |
        sort links_from_readme.txt | uniq > unique_links.txt

    - name: Commit unique links file
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add unique_links.txt
          git commit -m "Add unique links file $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
