name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ForkRules:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Create a folder to store the list file links
      run: mkdir -p QuantumultX_files

    - name: Recursive fetch of .list file links
      run: |
        REPO="blackmatrix7/ios_rule_script"
        BRANCH="master"
        DIR="rule/QuantumultX"
        
        # 定义递归函数获取 .list 文件的下载链接
        fetch_files() {
          local path=$1
          
          # 获取当前目录下的文件和子目录列表
          response=$(curl -s "https://api.github.com/repos/$REPO/contents/$path?ref=$BRANCH")
          
          # 循环处理目录和文件
          for item in $(echo "$response" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${item} | base64 --decode | jq -r ${1}
            }
            
            # 如果是文件且以 .list 结尾，输出下载链接
            if [[ $(_jq '.type') == "file" && $(_jq '.name') == *.list ]]; then
              echo $(_jq '.download_url') >> QuantumultX_files/list_files_links.txt
            fi
            
            # 如果是目录，递归调用
            if [[ $(_jq '.type') == "dir" ]]; then
              fetch_files $(_jq '.path')
            fi
          done
        }

        # 获取所有的 .list 文件下载链接并保存到文件
        fetch_files $DIR

    - name: Upload the list file links as artifact
      uses: actions/upload-artifact@v3
      with:
        name: quantumultx-list-files
        path: QuantumultX_files/list_files_links.txt

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
