name: Extract Links from README

on:
  workflow_dispatch:

jobs:
  ExtractLinks:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Clone the repository
      run: |
        echo "Cloning repository..."
        git clone https://github.com/blackmatrix7/ios_rule_script.git
        echo "Repository cloned."

    - name: Check current directory
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing contents of the repository:"
        ls -R

    - name: List contents of QuantumultX directory
      run: |
        echo "Listing contents of ios_rule_script/rule/QuantumultX:"
        ls -R ios_rule_script/rule/QuantumultX

    - name: Create folder for extracted links
      run: |
        mkdir -p QuantumultX_files
        echo "Folder for extracted links created."

    - name: Find README.md files and extract links
      run: |
        echo "Searching for README.md files..."
        find ./ios_rule_script/rule/QuantumultX -type f -name "README.md" | tee found_readmes.txt
        echo "Found README.md files listed in found_readmes.txt."
        
        # 从 README.md 文件中提取符合条件的链接并去重
        find ./ios_rule_script/rule/QuantumultX -type f -name "README.md" | while read file; do
          echo "Processing $file"
          
          # 使用 grep 提取符合条件的链接，并通过 sort -u 去重
          grep -o 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/[^"]*' "$file" >> QuantumultX_files/links_from_readme.txt
        done

        # 去重提取的链接
        sort -u QuantumultX_files/links_from_readme.txt -o QuantumultX_files/links_from_readme.txt
        echo "Links extracted and duplicates removed."

    - name: Check extracted links
      run: |
        echo "Extracted links:"
        cat QuantumultX_files/links_from_readme.txt

    - name: Upload extracted links as artifact
      uses: actions/upload-artifact@v3
      with:
        name: readme-links
        path: QuantumultX_files/links_from_readme.txt

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
