name: Extract Links from README

on:
  workflow_dispatch:

jobs:
  ExtractLinks:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Create folder for extracted links
      run: mkdir -p QuantumultX_files

    - name: Recursive fetch of README.md files and extract links
      run: |
        REPO="blackmatrix7/ios_rule_script"
        BRANCH="master"
        DIR="rule/QuantumultX"
        
        # 定义递归函数获取 README.md 文件中的下载链接
        fetch_readme_links() {
          local path=$1
          local page=1
          local per_page=100  # 每页获取的最大文件数量，GitHub API 默认最大为 100
          
          # 循环处理分页，直到获取所有文件
          while true; do
            # 获取当前目录下的文件和子目录列表
            response=$(curl -s "https://api.github.com/repos/$REPO/contents/$path?ref=$BRANCH&per_page=$per_page&page=$page")
            
            # 循环处理目录和文件
            for item in $(echo "$response" | jq -r '.[] | @base64'); do
              _jq() {
                echo ${item} | base64 --decode | jq -r ${1}
              }
              
              # 如果是 README.md 文件，获取其内容并提取链接
              if [[ $(_jq '.type') == "file" && $(_jq '.name') == "README.md" ]]; then
                readme_url=$(_jq '.download_url')
                readme_content=$(curl -s "$readme_url")

                # 使用 grep 提取包含特定下载链接的行，并保存到文件
                echo "$readme_content" | grep -o 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/[^"]*' >> QuantumultX_files/links_from_readme.txt
              fi
              
              # 如果是目录，递归调用
              if [[ $(_jq '.type') == "dir" ]]; then
                fetch_readme_links $(_jq '.path')
              fi
            done
            
            # 检查是否还有更多页
            if [[ $(curl -s -I "https://api.github.com/repos/$REPO/contents/$path?ref=$BRANCH&per_page=$per_page&page=$((page + 1))" | grep -i 'rel="next"') ]]; then
              page=$((page + 1))
            else
              break
            fi
          done
        }

        # 获取所有 README.md 文件中的下载链接并保存到文件
        fetch_readme_links $DIR

    - name: Upload extracted links as artifact
      uses: actions/upload-artifact@v3
      with:
        name: readme-links
        path: QuantumultX_files/links_from_readme.txt

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
