name: file links

on:
  workflow_dispatch:  # 通过手动触发工作流

jobs:
  ExtractLinks:
    runs-on: ubuntu-24.04  # 在 Ubuntu 24.04 环境下运行
    env:
      TZ: 'Asia/Shanghai'  # 设置时区为上海时间

    steps:
    # 步骤 1: 检出目标仓库
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2  # 使用 actions/checkout 获取当前仓库代码

    # 步骤 5: 删除 ios_rule_script 文件夹
    - name: Delete ios_rule_script folder
      run: |
        echo "Deleting ios_rule_script folder..."
        rm -rf ios_rule_script  # 删除整个 ios_rule_script 文件夹

    # 步骤 6: 添加并提交更改
    - name: Add and Commit
      run: |
        # 如果有更改，提交更改
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"  # 配置提交者邮箱
          git config --local user.name "GitHub Action"  # 配置提交者名字
          git add -A  # 添加所有更改
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"  # 提交更改
          git pull --rebase origin X  # 拉取远程 X 分支的最新提交
          git push origin X  # 推送本地更改到远程 X 分支
        else
          echo "No changes to commit."  # 如果没有更改，则输出提示信息
        fi

    # 清理工作流：删除历史工作流记录
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main  # 使用 Mattraks 的 GitHub Action 清理工作流记录
      with:
        retain_days: 0  # 不保留任何工作流记录
        keep_minimum_runs: 2  # 保留至少两个最小的工作流运行记录
