name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ForkRules:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Create a folder to store the list file links
      run: mkdir -p QuantumultX_files

    - name: Recursive fetch of .list file links
      run: |
        REPO="blackmatrix7/ios_rule_script"
        BRANCH="master"
        DIR="rule/QuantumultX"
        
        # Function to recursively fetch .list files
        fetch_files() {
          local path=$1
          # 获取当前目录下的文件和子目录列表
          curl -s "https://api.github.com/repos/$REPO/contents/$path?ref=$BRANCH" \
            | jq -r '.[] | 
                if .type == "file" and .name | endswith(".list") then
                  .download_url
                elif .type == "dir" then
                  # 递归调用获取子目录内容
                  fetch_files(.path)
                else
                  empty
                end'
        }

        # 获取所有的 .list 文件下载链接
        fetch_files $DIR > QuantumultX_files/list_files_links.txt

    - name: Check the list file links
      run: |
        cat QuantumultX_files/list_files_links.txt  # 打印出文件链接，查看是否获取到正确内容

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    - name: Upload the list file links
      uses: actions/upload-artifact@v3
      with:
        name: quantumultx-list-files
        path: QuantumultX_files/list_files_links.txt

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
