name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ForkRules:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y curl jq

    - name: Fetch .list Download Links
      run: |
        # 获取页面HTML内容
        curl -sL https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX > page.html

        # 提取 .list 文件相对路径
        grep -oP 'href=".*?\.list"' page.html |
        sed -e 's/href="//' -e 's/"//' |
        awk '{print "https://raw.githubusercontent.com"$0}' |
        sed 's/github.com/blackmatrix7\/ios_rule_script\/master/' > download_links.txt

        # 查看结果
        cat download_links.txt

    - name: Save Output
      run: |
        # 将文件保存到项目根目录
        mv download_links.txt ./new_download_links.txt

    # 添加并提交更改
    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
