name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ForkRules:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y curl jq

    - name: Fetch .list Download Links
      run: |
        # 获取页面HTML内容
        echo "Fetching page content..."
        curl -sL https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX > page.html
        
        # 打印页面内容进行调试
        echo "Page content saved in page.html:"
        cat page.html
        
        # 使用简单正则表达式提取所有包含 .list 的链接
        echo "Extracting .list file links..."
        grep -o 'href="[^"]*\.list"' page.html | \
        sed -e 's/href="//' -e 's/"//' > links.txt
        
        # 打印提取的链接进行调试
        echo "Extracted links:"
        cat links.txt
        
        # 生成可以直接下载的链接
        echo "Generating full download links..."
        awk '{print "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/"$0}' links.txt > download_links.txt
        
        # 打印最终的下载链接
        echo "Download links generated:"
        cat download_links.txt

    - name: Save Output
      run: |
        # 跳过复制操作，如果文件已存在
        if [ ! -f "./download_links.txt" ]; then
          cp download_links.txt ./download_links.txt
        else
          echo "File download_links.txt already exists, skipping copy."
        fi

    - name: Add and Commit
      run: |
        # 检查是否有更改
        if [[ -n $(git status -s) ]]; then
          echo "Changes detected, committing to the repository..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
