name: Fork Rules

on:
  workflow_dispatch:

jobs:
  ForkRules:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.2.2

    # 拉取 .list 文件下载链接并保存到 txt 文件
    - name: Fetch .list file links
      run: |
        # GitHub API URL
        GITHUB_API_URL="https://api.github.com/repos/blackmatrix7/ios_rule_script/contents/rule/QuantumultX"

        # 输出文件路径
        OUTPUT_FILE="quantumultx_list_links.txt"

        # 调试：查看 API 返回的完整数据
        echo "Fetching data from GitHub API..."
        curl -s $GITHUB_API_URL > response.json
        echo "API Response (First 500 chars):"
        head -n 20 response.json  # 输出前 20 行，方便调试

        # 检查返回的数据是否包含 .list 文件
        echo "Checking if .list files are present..."
        jq '.[] | .name' response.json

        # 过滤出 .list 文件的下载链接
        echo "Filtering .list file download links..."
        jq -r '.[] | select(.name | endswith(".list")) | .download_url' response.json > $OUTPUT_FILE

        # 打印提取的链接
        echo "Extracted download links:"
        cat $OUTPUT_FILE

    # 添加并提交更改
    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
